[Interface]
PrivateKey = <CLIENT PRIVATE KEY>
Address = <CLIENT IP ADDRESS> # 10.11.10.2/24, fd10:11:10::2/64
DNS = <DNS SERVERS> # 192.168.178.1, 1.1.1.1
Table = 1234
mtu = 1320

PreUp = ip rule add not from all fwmark 0x9 lookup 1234
PreUp = ip -6 rule add not from all fwmark 0x9 lookup 1234

PostDown = ip rule del not from all fwmark 0x9 lookup 1234
PostDown = ip -6 rule del not from all fwmark 0x9 lookup 1234

[Peer]
PublicKey = <SERVER PUBLIC KEY>
Endpoint = 127.0.0.1:51820
AllowedIPs = <ALLOWED IPs> # 0.0.0.0/0, 192.168.178.0/24, ::/0, fdc0:4b24:826a::0/64
PersistentKeepalive = 25
