# NOTE:
# This can be your normal, existing wireguard server. You most likely don't have to change anything on the server's wireguard config.
# You only need to install xray on the server and make it tunnel the wireguard traffic to the wireguard server.

[Interface]
Address = <SERVER ADDRESS> # 10.11.10.1/24, fd10:11:10::1/64
ListenPort = 51820
PrivateKey = <SERVER PRIVATE KEY>

# client 1
[Peer]
PublicKey = <CLIENT PUBLIC KEY>
AllowedIPs = <CLIENT ALLOWED IPs> # 10.11.10.2/32, fd10:11:10::2/128

# other clients
# [...]
